--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -98,4 +98,4 @@
           token: ${{ secrets.CODECOV_TOKEN }}
           plugins: gcov
           fail_ci_if_error: true
-          verbose: true
+          verbose: true